apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-kubeginners-deployment
 # namespace: kubeginners-app
  labels:
    app: eks-kubeginners-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-kubeginners-app
  template:
    metadata:
      labels:
        app: eks-kubeginners-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nginx
          image: hemanth0407/todo-app-kubeginners:v1
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
